# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tim Sullivan
email: tsullivan@timatooth.com
timezone: Pacific/Auckland
repository: timatooth/timatooth.github.io
description: >
  This is my tech blog of random programming stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timatooth.com"
twitter_username: timatooth
github_username:  timatooth
instagram_username: timatooth

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
show_excerpts: true

google_analytics: UA-86909821-1

disqus:
  shortname: timatooth
