# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Sullivan
email: tsullivan@timatooth.com
description: >
  Welcome to my photography and software development blog. I like to
  spend time tinkering in JavaScript making silly software ideas work.
baseurl: "" # the subpath of your site, e.g. /blog
staticurl: "/assets"
url: "http://timatooth.com" # the base hostname & protocol for your site
twitter_username: timatooth
github_username:  timatooth

# Build settings
markdown: kramdown
