# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Sullivan
email: tsullivan@timatooth.com
description: > 
  The photography and software development blog of Tim Sullivan. Located Dunedin, New Zealand. 
  I like to spend time tinkering with Python, JavaScript among many other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://timatooth.com" # the base hostname & protocol for your site
twitter_username: timatooth
github_username:  timatooth

# Build settings
markdown: kramdown
